name: hgit
version: 0.1.0.0

dependencies:
  - base == 4.*
  - attoparsec
  - attoparsec-binary
  - base16-bytestring
  - bytestring
  - conduit
  - conduit-extra
  - containers
  - cryptohash-sha1
  - directory
  - extra
  - filepath
  - filepattern
  - flatparse
  - http-conduit
  - http-types
  - mmap
  - mtl
  - optparse-applicative
  - pqueue
  - relude
  - stm
  - stm-conduit
  - string-conversions
  - template-haskell
  - text
  - time
  - transformers
  - unix
  - unliftio
  - vector
  - vector-algorithms
  - zlib

executables:
  hgit:
    main: Main.hs
    source-dirs: app

ghc-options:
  - -O2
  - -Wall
  - -Werror=missing-fields
  - -ferror-spans
  - -fno-warn-type-defaults
  - -fno-warn-unused-binds
  - -fno-warn-unused-do-bind
  - -fno-warn-unused-imports
  - -fwarn-incomplete-uni-patterns

default-extensions:
  - BinaryLiterals
  - InstanceSigs
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
