name: hgit
version: 0.1.0.0

dependencies:
  - base == 4.*
  - relude
  - directory
  - filepath
  - mtl
  - transformers
  - bytestring
  - cryptohash-sha1
  - base16-bytestring
  - zlib
  - optparse-applicative
  - attoparsec
  - attoparsec-binary
  - vector
  - vector-algorithms
  - containers
  - text
  - unix
  - extra
  - unliftio
  - filepattern

executables:
  hgit:
    main: Main.hs
    source-dirs: app

ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
  - -fno-warn-unused-binds
  - -fno-warn-unused-do-bind
  - -fno-warn-unused-imports
  - -fno-warn-type-defaults
  - -ferror-spans
  - -Werror=missing-fields
  - -O2

default-extensions:
  - NoImplicitPrelude
  - BinaryLiterals
  - InstanceSigs
  - RecordWildCards
  - OverloadedStrings
  - LambdaCase
