name: hgit
version: 0.1.0.0

dependencies:
  - base == 4.*
  - haskell-say

library:
  source-dirs: src

executables:
  hgit:
    main: Main.hs
    source-dirs: app
    dependencies:
      - hgit
      - optparse-applicative
